### ISSUE TITLE
Error when trying to receive from audacity

### ISSUE THREAD

**Issue by dimitarsp** [tin2tin/audacity_tools_for_blender#20]
Hi, I get an error when trying to receive from Audacity in 2.92 official

```
Python: Traceback (most recent call last):
  File "addons\audacity_tools_for_blender\operators\receive_from_audacity.py", line 107, in execute
    channel=find_completely_empty_channel(),
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_2.92.100.0_x64__ppwjx1n5r4v9t\Blender\2.92\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: File 'voiceover\voiceover_from_audacity.wav' could not be loaded


location: <unknown location>:-1
```

**Comment by tin2tin** [comment]
Hmm, can you open that file manually in Blender or is the file faulty?  

Can you describe your workflow up till that point?

**Comment by dimitarsp** [comment]
I am starting a blank timeline with text on track one and nothing else, and pressing record.  The file is not in the folder specified. Does Blender say to Audacity to save to wav file or should audacity be automatically saving the wav file?

**Comment by tin2tin** [comment]
Atm. Audacity is going through a lot of changes, which could be the cause of this. Try to find a pre 3.0 version of Audacity, and let us know if that works for you? (This should properly be investigated properly, but I don't have the time right now.)

**Comment by dimitarsp** [comment]
Yes, I am aware of the changes :). I actually had 2.4.2 installed and updated in the process to see whether the update could change anything, but it didn't. No worries, for the time being I've found a workaround with the Push to Talk addon. And thanks for making all these awesome addons that make Blender's video editor more usable!

Another bug - when pressing play within the audacity addon in blender, the timeline in audacity adjusts but the timeline in Blender does not - it stays still.

**Comment by tin2tin** [comment]
Try uninstalling it and download it again https://github.com/tin2tin/audacity_tools_for_blender/archive/refs/heads/main.zip and set it up to use Audacity 2.4.2.

Works for me:
![rec_audacity](https://user-images.githubusercontent.com/1322593/119952469-58789400-bf9d-11eb-9c43-45962343efc0.gif)


I did the Push to Talk Windows part, but the latency is just too high of ffmpeg... 

For play to work, you must fist send your strip to audacity, you can't record then switch to strip and then hit play.
