### ISSUE TITLE
Error sending audio strip

### ISSUE THREAD

**Issue by pistolario** [tin2tin/audacity_tools_for_blender#3]
Environment:
 * Audacity opened with mod_strip_pipe enabled
 * Blender opened in VSE with an audio strip selected
 * push "Send Strip" button

Result Error:
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/menda/.config/blender/2.92/scripts/addons/audacity_tools_for_blender-main/__init__.py", line 339, in execute
    do_command("SelectAll")
  File "/home/menda/.config/blender/2.92/scripts/addons/audacity_tools_for_blender-main/__init__.py", line 73, in do_command
    response = get_response()
  File "/home/menda/.config/blender/2.92/scripts/addons/audacity_tools_for_blender-main/__init__.py", line 59, in get_response
    line = FROMPIPE.readline()
NameError: name 'FROMPIPE' is not defined

location: <unknown location>:-1

**Comment by tin2tin** [comment]
You'll need to restart Audacity after changing the setting. 

And you'll need to restart Blender if you run the add-on once.

Both things should be described in the readme.

**Comment by pistolario** [comment]
Great! If I start Audacity first, then Blender, It works!!
But with  these errors in console
ython: Traceback (most recent call last):
  File "/home/menda/.config/blender/2.92/scripts/addons/audacity_tools_for_blender-main/__init__.py", line 358, in execute
    set_volume(strip, True)
  File "/home/menda/.config/blender/2.92/scripts/addons/audacity_tools_for_blender-main/__init__.py", line 288, in set_volume
    if not fade_curve:
UnboundLocalError: local variable 'fade_curve' referenced before assignment

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/menda/.config/blender/2.92/scripts/addons/audacity_tools_for_blender-main/__init__.py", line 358, in execute
    set_volume(strip, True)
  File "/home/menda/.config/blender/2.92/scripts/addons/audacity_tools_for_blender-main/__init__.py", line 288, in set_volume
    if not fade_curve:
UnboundLocalError: local variable 'fade_curve' referenced before assignment

**Comment by tin2tin** [comment]
I fixed the fade_curve error. I'll close this bug report. Let me know if you see it again.
